### ISSUE TITLE
Error  OperationFailed in get_file_ext

### ISSUE THREAD

**Issue by akim-muto** [cgtoolbox/HoudiniExprEditor#1]
Please change  
```if parm.expressionLanguage() == hou.exprLanguage.Python:```
to
```if parm.node().expressionLanguage() == hou.exprLanguage.Python:```
at line271, because breaking out of OperationFailed.

**Comment by cgtoolbox** [comment]
node.expressionLanguage() returns the default expression language for the node.
But we want here to get the specific parameter's expression language ( acutally, we only want to know if it's python or not ).
The hou.OperationFailed is raised if the parameter doesn't have any expression set, but it will be catched anyway ( line 275 ),  the file created will be a simple .txt file then.
